[data]
    partition = [0.7, 0.3]

[model]
    type = "Regression-Logistic"
    path = ""
    n_factor = 4
    n_class = 3

[train]
    lr = 0.01
    batch_size = 16
    shuffle_train = true
    shuffle_valid = true
    max_epoch = 64
    log_interval = 4

[path]
    root_dir = "D:/Users/lgfz1/Documents/fed_kgqa/"
    checkpoint = ""
    parameters = ""
    dataset = "data/classification/iris/data.csv"
    train_log = "src/projects/regular/iris/iris.log"
